trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /variables.tf
      - /main.tf
pool:
  vmImage: ubuntu-latest
variables:
  - group: hawaVB
steps:
  - task: >-
      ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: Install Terraform
  - script: terraform version
    displayName: Terraform Version
  - script: >-
      az login --service-principal -u $(tfazAppID) -p $(SPNPass) --tenant
      $(TNTid)
    displayName: Log Into Azure
  - script: >-
      terraform init
    displayName: Terraform Init
    workingDirectory: $(System.DefaultWorkingDirectory)
  - script: >-
      terraform plan -var="client_id=$(tfazAppID)"
      -var="client_secret=$(SPNPass)" -var="tenant_id=$(TNTid)"
      -var="subscription_id=$(SUBid)" -var="admin_password=$(VMAdminPass)"
      -out="out.plan"
    displayName: Terraform Plan
    workingDirectory: $(System.DefaultWorkingDirectory)
  - script: terraform apply out.plan
    displayName: Terraform Apply
    workingDirectory: $(System.DefaultWorkingDirectory)
