trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /tfazlabro/variables.tf
      - /tfazlabro/main.tf

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: hawaVB
  - name: tenant_id
    value: "7afe75ee-20fb-4e79-93a6-9881f786e2d8"
  - name: subscription_id
    value: "64208b73-267b-43b1-9bb1-649f128147e6"

steps:
  
  - task: TerraformInstaller@0
    displayName: install terraform
    inputs:
      terraformVersion: latest
      
  - script: terraform version
    displayName: Terraform Version
    
  - task: TerraformCLI@0
    inputs:
        command: 'init'
        backendType: 'local'
      
  
  - script: |
      tf_output=$(terraform output -json)
      tfazhh=$(echo $tf_output | jq -r '.tfazhh.value')
      SPNPass=$(echo $tf_output | jq -r '.SPNPass.value')
      STGPass=$(echo $tf_output | jq -r '.STGPass.value')
      echo "##vso[task.setvariable variable=tfazhh]$tfazhh"
      echo "##vso[task.setvariable variable=SPNPass]$SPNPass"
      echo "##vso[task.setvariable variable=STGPass]$STGPass"
      echo "tfazhh=$tfazhh"
      echo "SPNPass=$SPNPass"
      echo "STGPass=$STGPass"
    displayName: 'Get Terraform Outputs'

  - script: az login --service-principal --username $(tfazhh) --password $(SPNPass) --tenant $(tenant_id)
    displayName: 'Log Into Azure'

  - script: terraform init -backend-config=resource_group_name=$(rg_name) -backend-config="storage_account_name=$(storageAccount_name)" -backend-config="container_name=$(cont_name)" -backend-config="access_key=$(STGPass)" -backend-config="key=$(state_file)"
    displayName: "Terraform Init"
    workingDirectory: $(System.DefaultWorkingDirectory)/tfazlabro

  - script: terraform plan -var="client_id=$(tfazhh)" -var="client_secret=$(SPNPass)" -var="tenant_id=$(tenant_id)" -var="subscription_id=$(subscription_id)" -var="admin_password=$(VMAdminPass)" -out="out.plan"
    displayName: Terraform Plan
    workingDirectory: $(System.DefaultWorkingDirectory)/tfazlabro

  - script: terraform apply out.plan
    displayName: 'Terraform Apply'
    workingDirectory: $(System.DefaultWorkingDirectory)/tfazlabro