trigger:
  branches:
    include:
      - main
  paths:
    include:
      - tfazlabro/variables.tf
      - tfazlabro/main.tf

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: hawaVB

steps:
  - checkout: self

  - task: PowerShell@2
    displayName: 'Set Azure Service Principal Credentials'
    inputs:
      targetType: 'inline'
      script: |
        $env:ARM_CLIENT_ID = "$(tfazAppID)"
        $env:ARM_CLIENT_SECRET = "$(SPNPass)"
        $env:ARM_TENANT_ID = "$(tenant_id)"
        $env:ARM_SUBSCRIPTION_ID = "$(subscription_id)"

  - task: AzureCLI@2
    displayName: 'Install Azure CLI'

  - script: |
      echo "##vso[task.setvariable variable=tfazAppID;isOutput=true]$env:tfazAppID"
      echo "##vso[task.setvariable variable=SASPass;isOutput=true]$env:SASPass"
      echo "##vso[task.setvariable variable=tenant_id;isOutput=true]$env:tenant_id"
    displayName: 'Get Terraform Outputs'

  - script: |
      az login --service-principal -u $env:tfazAppID -p $env:SASPass --tenant $env:tenant_id
    displayName: 'Log Into Azure'

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: 'Install Terraform'

  - script: terraform version
    displayName: 'Terraform Version'

  - script: az login --service-principal -u $env:tfazAppID -p $env:SASPass --tenant $env:tenant_id
    displayName: 'Log Into Azure'

  - script: terraform init -backend-config=resource_group_name=$(rg_name) -backend-config="storage_account_name=$(storageAccount
