trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /tfazlabro/variables.tf
      - /tfazlabro/main.tf

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: hawaVB

steps:
  - task: TerraformInstaller@0
    displayName: install terraform
    inputs:
      terraformVersion: latest
      
  - script: terraform version
    displayName: Terraform Version
    
  - task: TerraformCLI@0
    inputs:
        command: 'init'
        backendType: 'local'
      
  - script: az login --service-principal --username $(tfazAppID) --password $(SPNPass) --tenant $(tenant-id)
    displayName: 'Log Into Azure'

  - script: terraform init -backend-config=resource_group_name=$(rg_name) -backend-config="storage_account_name=$(storageAccount_name)" -backend-config="container_name=$(cont_name)" -backend-config="access_key=$(STGPass)" -backend-config="key=$(state_file)"
    displayName: "Terraform Init"
    workingDirectory: $(System.DefaultWorkingDirectory)/tfazlabro

  - script: terraform plan -var="client_id=$(tfazAppID)" -var="client_secret=$(SPNPass)" -var="tenant_id=$(tenant-id)" -var="subscription_id=$(subscription_id)" -var="admin_password=$(VMAdminPass)" -out="out.plan"
    displayName: Terraform Plan
    workingDirectory: $(System.DefaultWorkingDirectory)/tfazlabro

  - script: terraform apply out.plan
    displayName: 'Terraform Apply'
    workingDirectory: $(System.DefaultWorkingDirectory)/tfazlabro