trigger:
  branches:
    include:
      - main

jobs:
- job: TerraformJob
  displayName: 'Terraform Deployment'
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    - group: hawaVB
  
  steps:
    - checkout: self
    - task: PowerShell@2
      displayName: 'Set Azure Service Principal Credentials'
      inputs:
        targetType: 'inline'
        script: |
          $env:ARM_CLIENT_ID = "$(SPNPass)"
          $env:ARM_CLIENT_SECRET = "$(SASPass)"
          $env:ARM_TENANT_ID = "$(tenant_id)"
          $env:ARM_SUBSCRIPTION_ID = "$(subscription_id)"

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: python -m pip install --upgrade pip
      displayName: 'Upgrade pip'

    - script: pip install azure-cli
      displayName: 'Install Azure CLI'

    - script: |
        echo "##vso[task.setvariable variable=storage_account_SASPass;isOutput=true]$(terraform output -raw outputvar)"
        echo "##vso[task.setvariable variable=pass_tfazsp;isOutput=true]$(terraform output -raw outputvar)"
        echo "##vso[task.setvariable variable=appid_tfazsp;isOutput=true]$(terraform output -raw outputvar)"
      displayName: 'Get Terraform Outputs'

    - script: |
        az login --service-principal -u $(SPNPass) -p $(SASPass) --tenant $(tenant_id)
      displayName: 'Log Into Azure'

    - script: |
        cd $(System.DefaultWorkingDirectory)/tfazlabro
        terraform init -backend-config=resource_group_name=$(rg_name) \
          -backend-config="storage_account_name=$(storageAccount_name)" \
          -backend-config="container_name=$(cont_name)" \
          -backend-config="access_key=$(storage_account_SASPass)" \
          -backend-config="key=$(state_file)"
        terraform plan -var="appid_tfazsp=$(SPNPass)" \
          -var="pass_tfazsp=$(SASPass)" \
          -var="tenant_id=$(tenant_id)" \
          -var="subscription_id=$(subscription_id)" \
          -var="VMAdminPass=$(VMAdminPass)" \
          -out="out.plan"
        terraform apply "out.plan"
      displayName: 'Terraform Init, Plan, and Apply'
