trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /TFAZLABRO/variables.tf
      - /TFAZLABRO/main.tf

jobs:
- job: TerraformJob
  displayName: 'Terraform Deployment'
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    - group: hawaVB
  
    - script: |
        az login --service-principal -u $(tfazAppID) -p $(SASPass) --tenant $(tenant_id)
      displayName: 'Log Into Azure'

    - script: |
        cd $(System.DefaultWorkingDirectory)/TFAZLABRO
        terraform init -backend-config=resource_group_name=$(rg_name) \
          -backend-config="storage_account_name=$(storageAccount_name)" \
          -backend-config="container_name=$(cont_name)" \
          -backend-config="access_key=$(storage_account_SASPass)" \
          -backend-config="key=$(state_file)"
        terraform plan -var="appid_tfazsp=$(tfazAppID)" \
          -var="pass_tfazsp=$(SASPass)" \
          -var="tenant_id=$(tenant_id)" \
          -var="subscription_id=$(subscription_id)" \
          -var="VMAdminPass=$(VMAdminPass)" \
          -out="out.plan"
        terraform apply "out.plan"
      displayName: 'Terraform Init, Plan, and Apply'